apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nextjs-app
        image: gcr.io/ece9016/nextjs-app:v12
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: POSTGRES_HOST
          value: "postgres-service"
        - name: DATABASE_URL
          # value: "postgresql://${db_username}:${db_password}@${POSTGRES_HOST}:5432/${db_name}"
          value: "postgresql://postgres:X9z@4bV!eU2wM8yP@postgres-service:5432/postgres-db"
        - name: db_name
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: dbname
        - name: db_username
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: username
        - name: db_password
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
