apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nextjs-app
        image: gcr.io/ece9016/nextjs-app:v1  
        ports:
        - containerPort: 3000              
        env:
        - name: DATABASE_URL               
          value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres-service:5432/$(POSTGRES_DB)"
        envFrom:                           
        - secretRef:
            name: postgres-secret
