apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nextjs-app
        image: gcr.io/ece9016/nextjs-app:v14
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: production
        - name: POSTGRES_HOST
          value: postgres-service
        - name: DATABASE_URL
          value: not set yet
        - name: db_name
          valueFrom:
            secretKeyRef:
              key: dbname
              name: postgres-secret
        - name: db_username
          valueFrom:
            secretKeyRef:
              key: username
              name: postgres-secret
        - name: db_password
          valueFrom:
            secretKeyRef:
              key: password
              name: postgres-secret
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - nginx
            topologyKey: "kubernetes.io/hostname"
      tolerations:
      - key: "app"
        operator: "Equal"
        value: "nginx"
        effect: "NoSchedule"
