apiVersion: batch/v1
kind: Job
metadata:
  name: prisma-migration-job
spec:
  template:
    spec:
      containers:
      - name: prisma-migration
        image: gcr.io/ece9016/nextjs-app:v12
        command: ["sh", "-c"]
        args: ["npx prisma migrate deploy --schema ./prisma/schema.prisma"]
        env:
          - name: DATABASE_URL
            value: "postgresql://postgres:X9z@4bV!eU2wM8yP@postgres-service:5432/postgres-db"
      restartPolicy: Never
  backoffLimit: 4
